"""Auto-generated item catalog (id -> English name). DO NOT EDIT BY HAND.
Generated 2026-07-14 by scripts/gen_items.py from
the MateusAquino/stardewids unpacked-asset mirror.
OBJECTS keys are unqualified object ids; BIG_CRAFTABLES keys are unqualified
big-craftable ids (note: object/big-craftable numeric ids can collide).
"""

OBJECTS = {
    '0': 'Weeds',
    '2': 'Diamond Stone',
    '4': 'Ruby Stone',
    '6': 'Jade Stone',
    '8': 'Amethyst Stone',
    '10': 'Topaz Stone',
    '12': 'Emerald Stone',
    '14': 'Aquamarine Stone',
    '16': 'Wild Horseradish',
    '18': 'Daffodil',
    '20': 'Leek',
    '22': 'Dandelion',
    '24': 'Parsnip',
    '25': 'Mussel Stone',
    '30': 'Lumber',
    '32': 'Stone',
    '34': 'Stone',
    '36': 'Stone',
    '38': 'Stone',
    '40': 'Stone',
    '42': 'Stone',
    '44': 'Gem Stone',
    '46': 'Mystic Stone',
    '48': 'Snowy Stone',
    '50': 'Snowy Stone',
    '52': 'Snowy Stone',
    '54': 'Snowy Stone',
    '56': 'Snowy Stone',
    '58': 'Snowy Stone',
    '60': 'Emerald',
    '62': 'Aquamarine',
    '64': 'Ruby',
    '66': 'Amethyst',
    '68': 'Topaz',
    '69': 'Banana Sapling',
    '70': 'Jade',
    '71': 'Trimmed Lucky Purple Shorts',
    '72': 'Diamond',
    '73': 'Golden Walnut',
    '74': 'Prismatic Shard',
    '75': 'Geode Stone',
    '76': 'Frozen Geode Stone',
    '77': 'Magma Geode Stone',
    '78': 'Cave Carrot',
    '79': 'Secret Note',
    '80': 'Quartz',
    '82': 'Fire Quartz',
    '84': 'Frozen Tear',
    '86': 'Earth Crystal',
    '88': 'Coconut',
    '90': 'Cactus Fruit',
    '91': 'Banana',
    '92': 'Sap',
    '93': 'Torch',
    '94': 'Spirit Torch',
    '95': 'Radioactive Stone',
    '96': 'Dwarf Scroll I',
    '97': 'Dwarf Scroll II',
    '98': 'Dwarf Scroll III',
    '99': 'Dwarf Scroll IV',
    '100': 'Chipped Amphora',
    '101': 'Arrowhead',
    '102': 'Lost Book',
    '103': 'Ancient Doll',
    '104': 'Elvish Jewelry',
    '105': 'Chewing Stick',
    '106': 'Ornamental Fan',
    '107': 'Dinosaur Egg',
    '108': 'Rare Disc',
    '109': 'Ancient Sword',
    '110': 'Rusty Spoon',
    '111': 'Rusty Spur',
    '112': 'Rusty Cog',
    '113': 'Chicken Statue',
    '114': 'Ancient Seed',
    '115': 'Prehistoric Tool',
    '116': 'Dried Starfish',
    '117': 'Anchor',
    '118': 'Glass Shards',
    '119': 'Bone Flute',
    '120': 'Prehistoric Handaxe',
    '121': 'Dwarvish Helm',
    '122': 'Dwarf Gadget',
    '123': 'Ancient Drum',
    '124': 'Golden Mask',
    '125': 'Golden Relic',
    '126': 'Strange Doll',
    '127': 'Strange Doll',
    '128': 'Pufferfish',
    '129': 'Anchovy',
    '130': 'Tuna',
    '131': 'Sardine',
    '132': 'Bream',
    '136': 'Largemouth Bass',
    '137': 'Smallmouth Bass',
    '138': 'Rainbow Trout',
    '139': 'Salmon',
    '140': 'Walleye',
    '141': 'Perch',
    '142': 'Carp',
    '143': 'Catfish',
    '144': 'Pike',
    '145': 'Sunfish',
    '146': 'Red Mullet',
    '147': 'Herring',
    '148': 'Eel',
    '149': 'Octopus',
    '150': 'Red Snapper',
    '151': 'Squid',
    '152': 'Seaweed',
    '153': 'Green Algae',
    '154': 'Sea Cucumber',
    '155': 'Super Cucumber',
    '156': 'Ghostfish',
    '157': 'White Algae',
    '158': 'Stonefish',
    '159': 'Crimsonfish',
    '160': 'Angler',
    '161': 'Ice Pip',
    '162': 'Lava Eel',
    '163': 'Legend',
    '164': 'Sandfish',
    '165': 'Scorpion Carp',
    '166': 'Treasure Chest',
    '167': 'Joja Cola',
    '168': 'Trash',
    '169': 'Driftwood',
    '170': 'Broken Glasses',
    '171': 'Broken CD',
    '172': 'Soggy Newspaper',
    '174': 'Large Egg',
    '176': 'Egg',
    '178': 'Hay',
    '180': 'Egg',
    '182': 'Large Egg',
    '184': 'Milk',
    '186': 'Large Milk',
    '188': 'Green Bean',
    '190': 'Cauliflower',
    '191': 'Ornate Necklace',
    '192': 'Potato',
    '194': 'Fried Egg',
    '195': 'Omelet',
    '196': 'Salad',
    '197': 'Cheese Cauliflower',
    '198': 'Baked Fish',
    '199': 'Parsnip Soup',
    '200': 'Vegetable Medley',
    '201': 'Complete Breakfast',
    '202': 'Fried Calamari',
    '203': 'Strange Bun',
    '204': 'Lucky Lunch',
    '205': 'Fried Mushroom',
    '206': 'Pizza',
    '207': 'Bean Hotpot',
    '208': 'Glazed Yams',
    '209': 'Carp Surprise',
    '210': 'Hashbrowns',
    '211': 'Pancakes',
    '212': 'Salmon Dinner',
    '213': 'Fish Taco',
    '214': 'Crispy Bass',
    '215': 'Pepper Poppers',
    '216': 'Bread',
    '218': 'Tom Kha Soup',
    '219': 'Trout Soup',
    '220': 'Chocolate Cake',
    '221': 'Pink Cake',
    '222': 'Rhubarb Pie',
    '223': 'Cookies',
    '224': 'Spaghetti',
    '225': 'Fried Eel',
    '226': 'Spicy Eel',
    '227': 'Sashimi',
    '228': 'Maki Roll',
    '229': 'Tortilla',
    '230': 'Red Plate',
    '231': 'Eggplant Parmesan',
    '232': 'Rice Pudding',
    '233': 'Ice Cream',
    '234': 'Blueberry Tart',
    '235': "Autumn's Bounty",
    '236': 'Pumpkin Soup',
    '237': 'Super Meal',
    '238': 'Cranberry Sauce',
    '239': 'Stuffing',
    '240': "Farmer's Lunch",
    '241': 'Survival Burger',
    '242': "Dish O' The Sea",
    '243': "Miner's Treat",
    '244': 'Roots Platter',
    '245': 'Sugar',
    '246': 'Wheat Flour',
    '247': 'Oil',
    '248': 'Garlic',
    '250': 'Kale',
    '251': 'Tea Sapling',
    '252': 'Rhubarb',
    '253': 'Triple Shot Espresso',
    '254': 'Melon',
    '256': 'Tomato',
    '257': 'Morel',
    '258': 'Blueberry',
    '259': 'Fiddlehead Fern',
    '260': 'Hot Pepper',
    '261': 'Warp Totem: Desert',
    '262': 'Wheat',
    '264': 'Radish',
    '265': 'Seafoam Pudding',
    '266': 'Red Cabbage',
    '267': 'Flounder',
    '268': 'Starfruit',
    '269': 'Midnight Carp',
    '270': 'Corn',
    '271': 'Unmilled Rice',
    '272': 'Eggplant',
    '273': 'Rice Shoot',
    '274': 'Artichoke',
    '275': 'Artifact Trove',
    '276': 'Pumpkin',
    '277': 'Wilted Bouquet',
    '278': 'Bok Choy',
    '279': 'Magic Rock Candy',
    '280': 'Yam',
    '281': 'Chanterelle',
    '282': 'Cranberries',
    '283': 'Holly',
    '284': 'Beet',
    '286': 'Cherry Bomb',
    '287': 'Bomb',
    '288': 'Mega Bomb',
    '289': 'Ostrich Egg',
    '290': 'Iron Stone',
    '292': 'Mahogany Seed',
    '293': 'Brick Floor',
    '294': 'Twig',
    '295': 'Twig',
    '296': 'Salmonberry',
    '297': 'Grass Starter',
    '298': 'Hardwood Fence',
    '299': 'Amaranth Seeds',
    '300': 'Amaranth',
    '301': 'Grape Starter',
    '302': 'Hops Starter',
    '303': 'Pale Ale',
    '304': 'Hops',
    '305': 'Void Egg',
    '306': 'Mayonnaise',
    '307': 'Duck Mayonnaise',
    '308': 'Void Mayonnaise',
    '309': 'Acorn',
    '310': 'Maple Seed',
    '311': 'Pine Cone',
    '313': 'Weeds',
    '314': 'Weeds',
    '315': 'Weeds',
    '316': 'Weeds',
    '317': 'Weeds',
    '318': 'Weeds',
    '319': 'Ice Crystal',
    '320': 'Ice Crystal',
    '321': 'Ice Crystal',
    '322': 'Wood Fence',
    '323': 'Stone Fence',
    '324': 'Iron Fence',
    '325': 'Gate',
    '326': 'Dwarvish Translation Guide',
    '328': 'Wood Floor',
    '329': 'Stone Floor',
    '330': 'Clay',
    '331': 'Weathered Floor',
    '333': 'Crystal Floor',
    '334': 'Copper Bar',
    '335': 'Iron Bar',
    '336': 'Gold Bar',
    '337': 'Iridium Bar',
    '338': 'Refined Quartz',
    '340': 'Honey',
    '341': 'Tea Set',
    '342': 'Pickles',
    '343': 'Stone',
    '344': 'Jelly',
    '346': 'Beer',
    '347': 'Rare Seed',
    '348': 'Wine',
    '349': 'Energy Tonic',
    '350': 'Juice',
    '351': 'Muscle Remedy',
    '368': 'Basic Fertilizer',
    '369': 'Quality Fertilizer',
    '370': 'Basic Retaining Soil',
    '371': 'Quality Retaining Soil',
    '372': 'Clam',
    '373': 'Golden Pumpkin',
    '376': 'Poppy',
    '378': 'Copper Ore',
    '380': 'Iron Ore',
    '382': 'Coal',
    '384': 'Gold Ore',
    '386': 'Iridium Ore',
    '388': 'Wood',
    '390': 'Stone',
    '392': 'Nautilus Shell',
    '393': 'Coral',
    '394': 'Rainbow Shell',
    '395': 'Coffee',
    '396': 'Spice Berry',
    '397': 'Sea Urchin',
    '398': 'Grape',
    '399': 'Spring Onion',
    '400': 'Strawberry',
    '401': 'Straw Floor',
    '402': 'Sweet Pea',
    '403': 'Field Snack',
    '404': 'Common Mushroom',
    '405': 'Wood Path',
    '406': 'Wild Plum',
    '407': 'Gravel Path',
    '408': 'Hazelnut',
    '409': 'Crystal Path',
    '410': 'Blackberry',
    '411': 'Cobblestone Path',
    '412': 'Winter Root',
    '413': 'Blue Slime Egg',
    '414': 'Crystal Fruit',
    '415': 'Stepping Stone Path',
    '416': 'Snow Yam',
    '417': 'Sweet Gem Berry',
    '418': 'Crocus',
    '419': 'Vinegar',
    '420': 'Red Mushroom',
    '421': 'Sunflower',
    '422': 'Purple Mushroom',
    '423': 'Rice',
    '424': 'Cheese',
    '425': 'Fairy Seeds',
    '426': 'Goat Cheese',
    '427': 'Tulip Bulb',
    '428': 'Cloth',
    '429': 'Jazz Seeds',
    '430': 'Truffle',
    '431': 'Sunflower Seeds',
    '432': 'Truffle Oil',
    '433': 'Coffee Bean',
    '434': 'Stardrop',
    '436': 'Goat Milk',
    '437': 'Red Slime Egg',
    '438': 'L. Goat Milk',
    '439': 'Purple Slime Egg',
    '440': 'Wool',
    '441': 'Explosive Ammo',
    '442': 'Duck Egg',
    '444': 'Duck Feather',
    '445': 'Caviar',
    '446': "Rabbit's Foot",
    '447': 'Aged Roe',
    '449': 'Stone Base',
    '450': 'Stone',
    '452': 'Weeds',
    '453': 'Poppy Seeds',
    '454': 'Ancient Fruit',
    '455': 'Spangle Seeds',
    '456': 'Algae Soup',
    '457': 'Pale Broth',
    '458': 'Bouquet',
    '459': 'Mead',
    '460': "Mermaid's Pendant",
    '461': 'Decorative Pot',
    '463': 'Drum Block',
    '464': 'Flute Block',
    '465': 'Speed-Gro',
    '466': 'Deluxe Speed-Gro',
    '472': 'Parsnip Seeds',
    '473': 'Bean Starter',
    '474': 'Cauliflower Seeds',
    '475': 'Potato Seeds',
    '476': 'Garlic Seeds',
    '477': 'Kale Seeds',
    '478': 'Rhubarb Seeds',
    '479': 'Melon Seeds',
    '480': 'Tomato Seeds',
    '481': 'Blueberry Seeds',
    '482': 'Pepper Seeds',
    '483': 'Wheat Seeds',
    '484': 'Radish Seeds',
    '485': 'Red Cabbage Seeds',
    '486': 'Starfruit Seeds',
    '487': 'Corn Seeds',
    '488': 'Eggplant Seeds',
    '489': 'Artichoke Seeds',
    '490': 'Pumpkin Seeds',
    '491': 'Bok Choy Seeds',
    '492': 'Yam Seeds',
    '493': 'Cranberry Seeds',
    '494': 'Beet Seeds',
    '495': 'Spring Seeds',
    '496': 'Summer Seeds',
    '497': 'Fall Seeds',
    '498': 'Winter Seeds',
    '499': 'Ancient Seeds',
    '516': 'Small Glow Ring',
    '517': 'Glow Ring',
    '518': 'Small Magnet Ring',
    '519': 'Magnet Ring',
    '520': 'Slime Charmer Ring',
    '521': 'Warrior Ring',
    '522': 'Vampire Ring',
    '523': 'Savage Ring',
    '524': 'Ring of Yoba',
    '525': 'Sturdy Ring',
    '526': "Burglar's Ring",
    '527': 'Iridium Band',
    '528': 'Jukebox Ring',
    '529': 'Amethyst Ring',
    '530': 'Topaz Ring',
    '531': 'Aquamarine Ring',
    '532': 'Jade Ring',
    '533': 'Emerald Ring',
    '534': 'Ruby Ring',
    '535': 'Geode',
    '536': 'Frozen Geode',
    '537': 'Magma Geode',
    '538': 'Alamite',
    '539': 'Bixite',
    '540': 'Baryte',
    '541': 'Aerinite',
    '542': 'Calcite',
    '543': 'Dolomite',
    '544': 'Esperite',
    '545': 'Fluorapatite',
    '546': 'Geminite',
    '547': 'Helvite',
    '548': 'Jamborite',
    '549': 'Jagoite',
    '550': 'Kyanite',
    '551': 'Lunarite',
    '552': 'Malachite',
    '553': 'Neptunite',
    '554': 'Lemon Stone',
    '555': 'Nekoite',
    '556': 'Orpiment',
    '557': 'Petrified Slime',
    '558': 'Thunder Egg',
    '559': 'Pyrite',
    '560': 'Ocean Stone',
    '561': 'Ghost Crystal',
    '562': 'Tigerseye',
    '563': 'Jasper',
    '564': 'Opal',
    '565': 'Fire Opal',
    '566': 'Celestine',
    '567': 'Marble',
    '568': 'Sandstone',
    '569': 'Granite',
    '570': 'Basalt',
    '571': 'Limestone',
    '572': 'Soapstone',
    '573': 'Hematite',
    '574': 'Mudstone',
    '575': 'Obsidian',
    '576': 'Slate',
    '577': 'Fairy Stone',
    '578': 'Star Shards',
    '579': 'Prehistoric Scapula',
    '580': 'Prehistoric Tibia',
    '581': 'Prehistoric Skull',
    '582': 'Skeletal Hand',
    '583': 'Prehistoric Rib',
    '584': 'Prehistoric Vertebra',
    '585': 'Skeletal Tail',
    '586': 'Nautilus Fossil',
    '587': 'Amphibian Fossil',
    '588': 'Palm Fossil',
    '589': 'Trilobite',
    '590': 'Artifact Spot',
    '591': 'Tulip',
    '593': 'Summer Spangle',
    '595': 'Fairy Rose',
    '597': 'Blue Jazz',
    '599': 'Sprinkler',
    '604': 'Plum Pudding',
    '605': 'Artichoke Dip',
    '606': 'Stir Fry',
    '607': 'Roasted Hazelnuts',
    '608': 'Pumpkin Pie',
    '609': 'Radish Salad',
    '610': 'Fruit Salad',
    '611': 'Blackberry Cobbler',
    '612': 'Cranberry Candy',
    '613': 'Apple',
    '614': 'Green Tea',
    '618': 'Bruschetta',
    '621': 'Quality Sprinkler',
    '628': 'Cherry Sapling',
    '629': 'Apricot Sapling',
    '630': 'Orange Sapling',
    '631': 'Peach Sapling',
    '632': 'Pomegranate Sapling',
    '633': 'Apple Sapling',
    '634': 'Apricot',
    '635': 'Orange',
    '636': 'Peach',
    '637': 'Pomegranate',
    '638': 'Cherry',
    '645': 'Iridium Sprinkler',
    '648': 'Coleslaw',
    '649': 'Fiddlehead Risotto',
    '651': 'Poppyseed Muffin',
    '668': 'Stone',
    '670': 'Stone',
    '674': 'Weeds',
    '675': 'Weeds',
    '676': 'Weeds',
    '677': 'Weeds',
    '678': 'Weeds',
    '679': 'Weeds',
    '680': 'Green Slime Egg',
    '681': 'Rain Totem',
    '682': 'Mutant Carp',
    '684': 'Bug Meat',
    '685': 'Bait',
    '686': 'Spinner',
    '687': 'Dressed Spinner',
    '688': 'Warp Totem: Farm',
    '689': 'Warp Totem: Mountains',
    '690': 'Warp Totem: Beach',
    '691': 'Barbed Hook',
    '692': 'Lead Bobber',
    '693': 'Treasure Hunter',
    '694': 'Trap Bobber',
    '695': 'Cork Bobber',
    '698': 'Sturgeon',
    '699': 'Tiger Trout',
    '700': 'Bullhead',
    '701': 'Tilapia',
    '702': 'Chub',
    '703': 'Magnet',
    '704': 'Dorado',
    '705': 'Albacore',
    '706': 'Shad',
    '707': 'Lingcod',
    '708': 'Halibut',
    '709': 'Hardwood',
    '710': 'Crab Pot',
    '715': 'Lobster',
    '716': 'Crayfish',
    '717': 'Crab',
    '718': 'Cockle',
    '719': 'Mussel',
    '720': 'Shrimp',
    '721': 'Snail',
    '722': 'Periwinkle',
    '723': 'Oyster',
    '724': 'Maple Syrup',
    '725': 'Oak Resin',
    '726': 'Pine Tar',
    '727': 'Chowder',
    '728': 'Fish Stew',
    '729': 'Escargot',
    '730': 'Lobster Bisque',
    '731': 'Maple Bar',
    '732': 'Crab Cakes',
    '733': 'Shrimp Cocktail',
    '734': 'Woodskip',
    '742': "Haley's Lost Bracelet",
    '745': 'Strawberry Seeds',
    '746': 'Jack-O-Lantern',
    '747': 'Rotten Plant',
    '748': 'Rotten Plant',
    '749': 'Omni Geode',
    '750': 'Weeds',
    '751': 'Copper Stone',
    '760': 'Stone',
    '762': 'Stone',
    '764': 'Gold Stone',
    '765': 'Iridium Stone',
    '766': 'Slime',
    '767': 'Bat Wing',
    '768': 'Solar Essence',
    '769': 'Void Essence',
    '770': 'Mixed Seeds',
    '771': 'Fiber',
    '772': 'Oil of Garlic',
    '773': 'Life Elixir',
    '774': 'Wild Bait',
    '775': 'Glacierfish',
    '784': 'Weeds',
    '785': 'Weeds',
    '786': 'Weeds',
    '787': 'Battery Pack',
    '788': 'Lost Axe',
    '789': 'Lucky Purple Shorts',
    '790': 'Berry Basket',
    '791': 'Golden Coconut',
    '792': 'Weeds',
    '793': 'Weeds',
    '794': 'Weeds',
    '795': 'Void Salmon',
    '796': 'Slimejack',
    '797': 'Pearl',
    '798': 'Midnight Squid',
    '799': 'Spook Fish',
    '800': 'Blobfish',
    '801': 'Wedding Ring',
    '802': 'Cactus Seeds',
    '803': 'Iridium Milk',
    '805': 'Tree Fertilizer',
    '807': 'Dinosaur Mayonnaise',
    '808': 'Void Ghost Pendant',
    '809': 'Movie Ticket',
    '810': 'Crabshell Ring',
    '811': 'Napalm Ring',
    '812': 'Roe',
    '814': 'Squid Ink',
    '815': 'Tea Leaves',
    '816': 'Fossil Stone',
    '817': 'Fossil Stone',
    '818': 'Clay Stone',
    '819': 'Omni Geode Stone',
    '820': 'Fossilized Skull',
    '821': 'Fossilized Spine',
    '822': 'Fossilized Tail',
    '823': 'Fossilized Leg',
    '824': 'Fossilized Ribs',
    '825': 'Snake Skull',
    '826': 'Snake Vertebrae',
    '827': 'Mummified Bat',
    '828': 'Mummified Frog',
    '829': 'Ginger',
    '830': 'Taro Root',
    '831': 'Taro Tuber',
    '832': 'Pineapple',
    '833': 'Pineapple Seeds',
    '834': 'Mango',
    '835': 'Mango Sapling',
    '836': 'Stingray',
    '837': 'Lionfish',
    '838': 'Blue Discus',
    '839': 'Thorns Ring',
    '840': 'Rustic Plank Floor',
    '841': 'Stone Walkway Floor',
    '842': 'Journal Scrap',
    '843': 'Cinder Shard Stone',
    '844': 'Cinder Shard Stone',
    '845': 'Stone',
    '846': 'Stone',
    '847': 'Stone',
    '848': 'Cinder Shard',
    '849': 'Copper Stone',
    '850': 'Iron Stone',
    '851': 'Magma Cap',
    '852': 'Dragon Tooth',
    '856': 'Curiosity Lure',
    '857': 'Tiger Slime Egg',
    '858': 'Qi Gem',
    '859': 'Lucky Ring',
    '860': 'Hot Java Ring',
    '861': 'Protection Ring',
    '862': 'Soul Sapper Ring',
    '863': 'Phoenix Ring',
    '864': 'War Memento',
    '865': 'Gourmet Tomato Salt',
    '866': 'Stardew Valley Rose',
    '867': 'Advanced TV Remote',
    '868': 'Arctic Shard',
    '869': 'Wriggling Worm',
    '870': "Pirate's Locket",
    '872': 'Fairy Dust',
    '873': 'Piña Colada',
    '874': 'Bug Steak',
    '875': 'Ectoplasm',
    '876': 'Prismatic Jelly',
    '877': 'Quality Bobber',
    '879': 'Monster Musk',
    '880': 'Combined Ring',
    '881': 'Bone Fragment',
    '882': 'Weeds',
    '883': 'Weeds',
    '884': 'Weeds',
    '885': 'Fiber Seeds',
    '886': 'Warp Totem: Island',
    '887': 'Immunity Band',
    '888': 'Glowstone Ring',
    '889': 'Qi Fruit',
    '890': 'Qi Bean',
    '891': 'Mushroom Tree Seed',
    '892': "Warp Totem: Qi's Arena",
    '893': 'Fireworks (Red)',
    '894': 'Fireworks (Purple)',
    '895': 'Fireworks (Green)',
    '896': 'Galaxy Soul',
    '897': "Pierre's Missing Stocklist",
    '898': 'Son of Crimsonfish',
    '899': 'Ms. Angler',
    '900': 'Legend II',
    '901': 'Radioactive Carp',
    '902': 'Glacierfish Jr.',
    '903': 'Ginger Ale',
    '904': 'Banana Pudding',
    '905': 'Mango Sticky Rice',
    '906': 'Poi',
    '907': 'Tropical Curry',
    '908': 'Magic Bait',
    '909': 'Radioactive Ore',
    '910': 'Radioactive Bar',
    '911': 'Horse Flute',
    '913': 'Enricher',
    '915': 'Pressure Nozzle',
    '917': 'Qi Seasoning',
    '918': 'Hyper Speed-Gro',
    '919': 'Deluxe Fertilizer',
    '920': 'Deluxe Retaining Soil',
    '921': 'Squid Ink Ravioli',
    '922': 'SupplyCrate',
    '923': 'SupplyCrate',
    '924': 'SupplyCrate',
    '925': 'Slime Crate',
    '926': 'Cookout Kit',
    '927': 'Camping Stove',
    '928': 'Golden Egg',
    '929': 'Hedge',
    '930': '???',
    'BasicCoalNode0': 'Stone',
    'BasicCoalNode1': 'Stone',
    'BlueGrassStarter': 'Blue Grass Starter',
    'Book_AnimalCatalogue': 'Animal Catalogue',
    'Book_Artifact': 'Treasure Appraisal Guide',
    'Book_Bombs': 'Dwarvish Safety Manual',
    'Book_Crabbing': "The Art O' Crabbing",
    'Book_Defense': 'Jack Be Nimble, Jack Be Thick',
    'Book_Diamonds': 'The Diamond Hunter',
    'Book_Friendship': 'Friendship 101',
    'Book_Grass': "Ol' Slitherlegs",
    'Book_Horse': 'Horse: The Book',
    'Book_Marlon': 'Mapping Cave Systems',
    'Book_Mystery': 'Book of Mysteries',
    'Book_PriceCatalogue': 'Price Catalogue',
    'Book_QueenOfSauce': 'Queen Of Sauce Cookbook',
    'Book_Roe': 'Jewels Of The Sea',
    'Book_Speed': 'Way Of The Wind pt. 1',
    'Book_Speed2': 'Way Of The Wind pt. 2',
    'Book_Trash': 'The Alleyway Buffet',
    'Book_Void': 'Monster Compendium',
    'Book_WildSeeds': 'Raccoon Journal',
    'Book_Woodcutting': "Woody's Secret",
    'Broccoli': 'Broccoli',
    'BroccoliSeeds': 'Broccoli Seeds',
    'ButterflyPowder': 'Butterfly Powder',
    'CalicoEgg': 'Calico Egg',
    'CalicoEggStone_0': 'Calico Egg Stone',
    'CalicoEggStone_1': 'Calico Egg Stone',
    'CalicoEggStone_2': 'Calico Egg Stone',
    'Carrot': 'Carrot',
    'CarrotSeeds': 'Carrot Seeds',
    'CaveJelly': 'Cave Jelly',
    'ChallengeBait': 'Challenge Bait',
    'DeluxeBait': 'Deluxe Bait',
    'DriedFruit': 'Dried',
    'DriedMushrooms': 'Dried',
    'FarAwayStone': 'Far Away Stone',
    'Goby': 'Goby',
    'GoldCoin': 'Gold Coin',
    'GoldenAnimalCracker': 'Golden Animal Cracker',
    'GoldenBobber': 'Golden Bobber',
    'GoldenMysteryBox': 'Golden Mystery Box',
    'GreenRainWeeds0': 'Green Rain Weeds',
    'GreenRainWeeds1': 'Green Rain Weeds',
    'GreenRainWeeds2': 'Green Rain Weeds',
    'GreenRainWeeds3': 'Green Rain Weeds',
    'GreenRainWeeds4': 'Green Rain Weeds',
    'GreenRainWeeds5': 'Green Rain Weeds',
    'GreenRainWeeds6': 'Green Rain Weeds',
    'GreenRainWeeds7': 'Green Rain Weeds',
    'MixedFlowerSeeds': 'Mixed Flower Seeds',
    'Moss': 'Moss',
    'MossSoup': 'Moss Soup',
    'MossySeed': 'Mossy Seed',
    'MysteryBox': 'Mystery Box',
    'MysticSyrup': 'Mystic Syrup',
    'MysticTreeSeed': 'Mystic Tree Seed',
    'PetLicense': 'Pet License',
    'PotOfGold': 'Stone',
    'Powdermelon': 'Powdermelon',
    'PowdermelonSeeds': 'Powdermelon Seeds',
    'PrizeTicket': 'Prize Ticket',
    'PurpleBook': 'Book Of Stars',
    'Raisins': 'Raisins',
    'RiverJelly': 'River Jelly',
    'SeaJelly': 'Sea Jelly',
    'SeedSpot': 'Artifact Spot',
    'SkillBook_0': 'Stardew Valley Almanac',
    'SkillBook_1': 'Bait And Bobber',
    'SkillBook_2': "Woodcutter's Weekly",
    'SkillBook_3': 'Mining Monthly',
    'SkillBook_4': 'Combat Quarterly',
    'SmokedFish': 'Smoked',
    'SonarBobber': 'Sonar Bobber',
    'SpecificBait': 'Bait',
    'StardropTea': 'Stardrop Tea',
    'SummerSquash': 'Summer Squash',
    'SummerSquashSeeds': 'Summer Squash Seeds',
    'TentKit': 'Tent Kit',
    'TreasureTotem': 'Treasure Totem',
    'TroutDerbyTag': 'Golden Tag',
    'VolcanoCoalNode0': 'Stone',
    'VolcanoCoalNode1': 'Stone',
    'VolcanoGoldNode': 'Gold Stone',
}

BIG_CRAFTABLES = {
    '0': 'House Plant',
    '1': 'House Plant',
    '2': 'House Plant',
    '3': 'House Plant',
    '4': 'House Plant',
    '5': 'House Plant',
    '6': 'House Plant',
    '7': 'House Plant',
    '8': 'Scarecrow',
    '9': 'Lightning Rod',
    '10': 'Bee House',
    '12': 'Keg',
    '13': 'Furnace',
    '15': 'Preserves Jar',
    '16': 'Cheese Press',
    '17': 'Loom',
    '19': 'Oil Maker',
    '20': 'Recycling Machine',
    '21': 'Crystalarium',
    '22': 'Table Piece L',
    '23': 'Table Piece R',
    '24': 'Mayonnaise Machine',
    '25': 'Seed Maker',
    '26': 'Wood Chair',
    '27': 'Wood Chair',
    '28': 'Skeleton Model',
    '29': 'Obelisk',
    '31': 'Chicken Statue',
    '32': 'Stone Cairn',
    '33': 'Suit Of Armor',
    '34': 'Sign Of The Vessel',
    '35': 'Basic Log',
    '36': 'Lawn Flamingo',
    '37': 'Wood Sign',
    '38': 'Stone Sign',
    '39': 'Dark Sign',
    '40': 'Big Green Cane',
    '41': 'Green Canes',
    '42': 'Mixed Cane',
    '43': 'Red Canes',
    '44': 'Big Red Cane',
    '45': 'Ornamental Hay Bale',
    '46': 'Log Section',
    '47': 'Grave Stone',
    '48': 'Seasonal Decor',
    '52': 'Stone Frog',
    '53': 'Stone Parrot',
    '54': 'Stone Owl',
    '55': 'Stone Junimo',
    '56': 'Slime Ball',
    '62': 'Garden Pot',
    '64': 'Bookcase',
    '65': 'Fancy Table',
    '66': 'Ancient Table',
    '67': 'Ancient Stool',
    '68': 'Grandfather Clock',
    '69': 'Teddy Timer',
    '70': 'Dead Tree',
    '71': 'Staircase',
    '72': 'Tall Torch',
    '73': 'Ritual Mask',
    '74': 'Bonfire',
    '75': 'Bongo',
    '76': 'Decorative Spears',
    '78': 'Boulder',
    '79': 'Door',
    '80': 'Door',
    '81': 'Locked Door',
    '82': 'Locked Door',
    '83': 'Wicked Statue',
    '84': 'Wicked Statue',
    '85': 'Sloth Skeleton L',
    '86': 'Sloth Skeleton M',
    '87': 'Sloth Skeleton R',
    '88': 'Standing Geode',
    '89': 'Obsidian Vase',
    '90': 'Bone Mill',
    '94': 'Singing Stone',
    '95': 'Stone Owl',
    '96': 'Strange Capsule',
    '98': 'Empty Capsule',
    '99': 'Feed Hopper',
    '101': 'Incubator',
    '104': 'Heater',
    '105': 'Tapper',
    '106': 'Camera',
    '107': 'Plush Bunny',
    '108': "Tub o' Flowers",
    '110': 'Rarecrow',
    '111': 'Decorative Pitcher',
    '112': 'Dried Sunflowers',
    '113': 'Rarecrow',
    '114': 'Charcoal Kiln',
    '116': 'Stardew Hero Trophy',
    '117': 'Soda Machine',
    '118': 'Barrel',
    '119': 'Crate',
    '120': 'Barrel',
    '121': 'Crate',
    '122': 'Barrel',
    '123': 'Crate',
    '124': 'Barrel',
    '125': 'Crate',
    '126': 'Rarecrow',
    '127': 'Statue Of Endless Fortune',
    '128': 'Mushroom Box',
    '130': 'Chest',
    '136': 'Rarecrow',
    '137': 'Rarecrow',
    '138': 'Rarecrow',
    '139': 'Rarecrow',
    '140': 'Rarecrow',
    '141': 'Prairie King Arcade System',
    '143': 'Wooden Brazier',
    '144': 'Stone Brazier',
    '145': 'Gold Brazier',
    '146': 'Campfire',
    '147': 'Stump Brazier',
    '148': 'Carved Brazier',
    '149': 'Skull Brazier',
    '150': 'Barrel Brazier',
    '151': 'Marble Brazier',
    '152': 'Wood Lamp-post',
    '153': 'Iron Lamp-post',
    '154': 'Worm Bin',
    '155': '??HMTGF??',
    '156': 'Slime Incubator',
    '158': 'Slime Egg-Press',
    '159': 'Junimo Kart Arcade System',
    '160': 'Statue Of Perfection',
    '161': '??Pinky Lemon??',
    '162': '??Foroguemon??',
    '163': 'Cask',
    '164': 'Solid Gold Lewis',
    '165': 'Auto-Grabber',
    '167': 'Deluxe Scarecrow',
    '174': 'Barrel',
    '175': 'Crate',
    '182': 'Geode Crusher',
    '184': 'Seasonal Plant',
    '188': 'Seasonal Plant',
    '192': 'Seasonal Plant',
    '196': 'Seasonal Plant',
    '200': 'Seasonal Plant',
    '204': 'Seasonal Plant',
    '208': 'Workbench',
    '209': 'Mini-Jukebox',
    '211': 'Wood Chipper',
    '214': 'Telephone',
    '216': 'Mini-Fridge',
    '219': 'Cursed P.K. Arcade System',
    '221': 'Item Pedestal',
    '231': 'Solar Panel',
    '232': 'Stone Chest',
    '238': 'Mini-Obelisk',
    '239': 'Farm Computer',
    '246': 'Coffee Maker',
    '247': 'Sewing Machine',
    '248': 'Mini-Shipping Bin',
    '254': 'Ostrich Incubator',
    '256': 'Junimo Chest',
    '262': 'Barrel',
    '263': 'Crate',
    '264': 'Heavy Tapper',
    '265': 'Deconstructor',
    '272': 'Auto-Petter',
    '275': 'Hopper',
    '278': 'Campfire',
    '280': 'Statue Of True Perfection',
    'Anvil': 'Anvil',
    'BaitMaker': 'Bait Maker',
    'BigChest': 'Big Chest',
    'BigStoneChest': 'Big Stone Chest',
    'Dehydrator': 'Dehydrator',
    'DeluxeWormBin': 'Deluxe Worm Bin',
    'FishSmoker': 'Fish Smoker',
    'HeavyFurnace': 'Heavy Furnace',
    'MiniForge': 'Mini-Forge',
    'MushroomLog': 'Mushroom Log',
    'StatueOfBlessings': 'Statue Of Blessings',
    'StatueOfTheDwarfKing': 'Statue Of The Dwarf King',
    'TextSign': 'Text Sign',
}
